In [2]:
## Import a bunch of modules that may be helpful
import numpy as np
import scipy as sp
import matplotlib as mpl
import matplotlib.cm as cm
import matplotlib.pyplot as plt
import pandas
import os
import time
import seaborn as sns
import requests


## Bagged Decision Trees for Classification
from sklearn import model_selection
from sklearn.ensemble import BaggingClassifier
from sklearn.tree import DecisionTreeClassifier


In [59]:
import csv 
header_reader = csv.reader(open("./Matlab_Files/joined_shots_2013.csv",'r'),delimiter = ',')
headers = set(next(header_reader))
print (headers)

#How many headers we have after deleted duplicated ones 
#this does not match with the data that we are trying to use
# There are two game id's 


#main_reader = csv.reader(open("./Matlab_Files/joined_shots_updated2013.csv",'r'),delimiter = ',')
dataframe = pandas.read_csv("./Matlab_Files/joined_shots_updated2013.csv",delimiter = ',',header =None)
array = dataframe.values

column_len = len(dataframe.columns)
columns = dataframe.columns

X = array[:,0:35]
Y = array[:,35]


seed = 5
kfold = model_selection.KFold(n_splits=2, random_state=seed)

# for train_indices, test_indices in kfold.split(X):
#       print('Train: %s | test: %s' % (train_indices, test_indices))

# print(train_indices)        
# print(test_indices)    


# for train_label_indices, test_label_indices in kfold.split(Y):
#       print('Train Label: %s | test label: %s' % (train_indices, test_indices))

print(train_label_indices)        
print(test_label_indices)    

whatis = X[train_indices,:]
print(whatis)

whatis2 = Y[train_label_indices]
print(whatis2)

    

{'', 'PTS', 'GAME_EVENT_ID', 'PERIOD', 'DRIBBLES', 'LOCATION', 'SHOT_TYPE', 'LOC_X', 'SHOT_CLOCK', 'SECONDS_REMAINING', 'CLOSEST_DEFENDER_PLAYER_ID', 'SHOT_MADE_FLAG', 'SHOT_DISTANCE', 'EVENT_TYPE', 'GAME_CLOCK', 'W', 'SHOT_ATTEMPTED_FLAG', 'GAME_ID', 'MATCHUP', 'LOC_Y', 'PTS_TYPE', 'GRID_TYPE', 'MINUTES_REMAINING', 'SHOT_ZONE_AREA', 'TOUCH_TIME', 'TEAM_ID', 'SHOT_DIST', 'SHOT_ZONE_RANGE', 'FGM', 'FINAL_MARGIN', 'SHOT_ZONE_BASIC', 'ACTION_TYPE', 'SHOT_RESULT', 'PLAYER_NAME', 'CLOSE_DEF_DIST', 'CLOSEST_DEFENDER', 'PLAYER_ID', 'SHOT_NUMBER'}
[     0      1      2 ... 100479 100480 100481]
[100482 100483 100484 ... 200960 200961 200962]
[[ 0.0000e+00  2.0232e+05  1.9000e+00 ... -4.0000e+01  5.3000e+01
   1.0000e+00]
 [ 1.0000e+00  2.0232e+05  3.2000e+00 ...  1.8200e+02  1.9500e+02
   1.0000e+00]
 [ 2.0000e+00  2.0349e+05  3.5000e+00 ...  1.5900e+02  2.0600e+02
   1.0000e+00]
 ...
 [ 4.0000e+00  2.0350e+05  7.0000e-01 ...  8.9000e+01  2.8000e+01
   1.0000e+00]
 [ 5.0000e+00  2.5550e+03  1.

In [53]:
url = "https://raw.githubusercontent.com/jbrownlee/Datasets/master/pima-indians-diabetes.data.csv"
names = ['preg', 'plas', 'pres', 'skin', 'test', 'mass', 'pedi', 'age', 'class']
dataframe = pandas.read_csv(url, names=names)
array = dataframe.values
X = array[:,0:8]
Y = array[:,8]



In [60]:
##

cart = DecisionTreeClassifier()
num_trees = 10

model = BaggingClassifier(base_estimator=cart, n_estimators=num_trees, random_state=seed)


results = model_selection.cross_val_score(model, X, Y, cv=kfold)
print(results)
print(results.mean())


[1. 1.]
1.0


[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
